name: Production Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install modules
      run: |
        npm install
    - name: Production Build
      run: |
        # Because quarkly may override changes in gatsby-config.js when commit from editor, we should patch dynamically.
        sed -i '/module.exports = {/a assetPrefix: "https:\/\/seo-microlandings-cdn.ukit.com",' gatsby-config.js
        PREFIX_PATHS=true npm run build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: "ru-central1"
        AWS_S3_ENDPOINT: "https://storage.yandexcloud.net"
        SOURCE_DIR: "public"
